### ISSUE TITLE
Project filters not preserved when clicking back button in browser 

### ISSUE THREAD

**Issue by ryangsteele** [aweber/imbi#40]
While filtering on the projects page works, if you click on one of the filtered results and then click the 'back' button in your browser, all of the filtering is lost.

Similarly, when pasting in a URL containing project filters, such as https://imbi.example.com/ui/projects?namespace_id=6&project_type_id=16&sort=namespace+asc%2Cname+asc&limit=25&offset=0, Imbi strips those params out of the URL out and all filtering is lost. 

I suspect these are both due to the same bug.

**Comment by gmr** [comment]
I have a fix for this pending.

**Comment by gmr** [comment]
Will be fixed in 0.9.0
