### ISSUE TITLE
Python code is not yapf formatted

### ISSUE THREAD

**Issue by cknave** [aweber/imbi#46]
The [code formatting section of CONTRIBUTING.md](https://github.com/aweber/imbi/blob/main/CONTRIBUTING.md#code-formatting) requires that new code is yapf formatted, but the existing python code is not. Here's the [differences from today, April 2, 2021](https://github.com/aweber/imbi/compare/4f86461af20a2b570e8017d0453d1af1eeb9c69a...cknave:yapf). 

Because of the unrelated changes this would add, I'm not running yapf when making PRs.

After updating the current codebase, it might make sense to pin the yapf version and check for formatting in the CI tests and git pre-commit hook to keep this stable.

I also recommend these yapf settings if you don't mind straying from the defaults:
```ini
[yapf]
allow_multiline_dictionary_keys = True
allow_split_before_dict_value = False
```

**Comment by gmr** [comment]
Or just remove that in from CONTRIBUTING and just require PEP8, which flake8 checks for. Thoughts?
