### ISSUE TITLE
Healthscore column sort doesn't actually sort.

### ISSUE THREAD

**Issue by tomkulzer** [aweber/imbi#47]
Clicking the "health score" column header that has sort icons on it doesn't actually change the sort order.
I did this by looking at the "project by namespace" view, but other views such as "projects by type" show similar behavior.

https://*/ui/projects?include_archived=false&namespace_id=2&sort=namespace+asc%2Cname+asc%2Cproject_score+desc&limit=25&offset=0

<img width="228" alt="2021-04-07_00-17-48" src="https://user-images.githubusercontent.com/6731107/113809718-b7a4ef80-9736-11eb-8764-f0d3f510aea9.png">

**Comment by tomkulzer** [comment]
my mistake, I was sorting multiple columns.  remove the sorts on the other columns and then this shows expected results.

**Comment by gmr** [comment]
We really need to make the behavior here more obvious and easier to reason about. I've solicited feedback from our UI/UX team on how to improve it.
