### ISSUE TITLE
Make full column header clickable for sort.

### ISSUE THREAD

**Issue by tomkulzer** [aweber/imbi#6]
Current: You have to click the tiny arrows on the left side of the column header to sort it.

Desire: Click anywhere in the column header to sort.

<img width="707" alt="2021-03-19_15-29-38" src="https://user-images.githubusercontent.com/6731107/111833082-01cd4a80-88c8-11eb-9fa0-8dfb98583672.png">

**Comment by gmr** [comment]
Will be addressed in the next release.
