### ISSUE TITLE
Ability to right click or middle click on projects to open in new tabs.

### ISSUE THREAD

**Issue by tomkulzer** [aweber/imbi#8]
When looking at all the projects in a big list, it'd make updating them faster if you could right click or middle click and open a bunch of projects in new tabs. I believe this means the project names need actual links rather than React onclick events. 

Having links that visually differentiate showing visited and unvisited projects is also handy. That just utilizes your browser history and link colors.  ":visited" CSS property.

/ui/projects?sort_name=asc&limit=25&offset=0&namespace=5

<img width="1148" alt="2021-03-19_16-05-21" src="https://user-images.githubusercontent.com/6731107/111836623-fb8d9d00-88cc-11eb-8f26-fb1e8e5eb0fb.png">

**Comment by gmr** [comment]
Is addressed and will be released in v0.10 - note that due to the nature of being a react app, it will have to load the app in each new window.
